#!/bin/bash

cat << EOF0 > ${DIRRUN}/degrib.bash 
#!/bin/bash -x
#PBS -N ${DEGRIB_jobname}
#PBS -q ${DEGRIB_QUEUE}
#PBS -l select=${DEGRIB_nnodes}:ncpus=${DEGRIB_ncpn}:mpiprocs=${DEGRIB_ncpn}
#PBS -l place=scatter
#PBS -l place=excl
#PBS -l walltime=${STATIC_walltime}
#PBS -j oe
#PBS -o ${DATAOUT}/${YYYYMMDDHHi}/Pre/logs/degrib.o$PBS_JOBID
#PBS -e ${DATAOUT}/${YYYYMMDDHHi}/Pre/logs/degrib.e$PBS_JOBID


ulimit -s unlimited
ulimit -c unlimited
ulimit -v unlimited

export PMIX_MCA_gds=hash


export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:${HOME}/local/lib64

cd ${DIRRUN}
. ${SCRIPTS}/setenv.bash

ldd ungrib.exe

rm -f GRIBFILE.* namelist.wps


sed -e "s,#LABELI#,${start_date},g;s,#PREFIX#,GFS,g" \
	${DIRRUN}/namelist.wps.TEMPLATE > ${DIRRUN}/namelist.wps

./link_grib.csh ${DATAIN}/${YYYYMMDDHHi}/gfs.t${YYYYMMDDHHi:8:2}z.pgrb2.0p25.f000.${YYYYMMDDHHi}.grib2

date
time mpirun -np 1 ./ungrib.exe
#time mpirun -np 1 ungrib.exe           # module load ungrib/4.5
date


grep "Successful completion of program ungrib.exe" ${DIRRUN}/ungrib.log >& /dev/null

if [ \$? -ne 0 ]; then
   echo "  BUMMER: Ungrib generation failed for some yet unknown reason."
   echo " "
   tail -10 ${DIRRUN}/ungrib.log
   echo " "
   exit 21
fi

#
# clean up and remove links
#
   mv ungrib.log ${DATAOUT}/${YYYYMMDDHHi}/Pre/logs/ungrib.${start_date}.log
   mv namelist.wps ${DATAOUT}/${YYYYMMDDHHi}/Pre/logs/namelist.${start_date}.wps
   mv GFS\:${start_date:0:13} ${DATAOUT}/${YYYYMMDDHHi}/Pre

   rm -fr ${DATAIN}/${YYYYMMDDHHi}

echo "End of degrib Job"


EOF0
