#!/bin/bash

cat << EOF0 > ${DIRRUN}/static.bash
#!/bin/bash -x
#SBATCH --job-name=${STATIC_jobname}
#SBATCH --nodes=${STATIC_nnodes}
#SBATCH --ntasks=${STATIC_ncores}
#SBATCH --tasks-per-node=${STATIC_ncpn}
#SBATCH --partition=${STATIC_QUEUE}
#SBATCH --time=${STATIC_walltime}
#SBATCH --output=${DATAOUT}/logs/static.bash.o%j    # File name for standard output
#SBATCH --error=${DATAOUT}/logs/static.bash.e%j     # File name for standard error output
#SBATCH --exclusive
##SBATCH --mem=500000


export executable=init_atmosphere_model

ulimit -s unlimited
ulimit -c unlimited
ulimit -v unlimited

. ${SCRIPTS}/setenv.bash

cd ${DIRRUN}

date
time mpirun -np \${SLURM_NTASKS} ./\${executable}
date

grep "Finished running" log.init_atmosphere.0000.out >& /dev/null
if [ \$? -ne 0 ]; then
   echo "  BUMMER: Static generation failed for some yet unknown reason."
   echo " "
   tail -10 ${STATICPATH}/log.init_atmosphere.0000.out
   echo " "
   exit 21
fi

echo "  ####################################"
echo "  ### Static completed - \$(date) ####"
echo "  ####################################"
echo " "


mv log.init_atmosphere.0000.out ${DATAOUT}/logs/log.init_atmosphere.0000.x1.${RES}.static.nc.out


EOF0
