#!/bin/bash

cat << EOF0 > ${DIRRUN}/static.bash
#!/bin/bash -x
#PBS -N ${STATIC_jobname}
#PBS -q ${STATIC_QUEUE}
#PBS -l select=${STATIC_nnodes}:ncpus=${STATIC_ncpn}:mpiprocs=${STATIC_ncpn}
#PBS -l place=scatter
#PBS -l place=excl
#PBS -l walltime=${STATIC_walltime}
#PBS -j oe
#PBS -o ${DATAOUT}/logs/static.bash.o${PBS_JOBID}
#PBS -e ${DATAOUT}/logs/static.bash.e${PBS_JOBID}


export executable=init_atmosphere_model

ulimit -s unlimited
ulimit -c unlimited
ulimit -v unlimited

. ${SCRIPTS}/setenv.bash

cd ${DIRRUN}


export CURRENT_HOST=\$(cat \$PBS_NODEFILE)
export HOSTFILE=${DIRRUN}/hostfile
echo "\${CURRENT_HOST}" | sed "s,\..*$,," > \${HOSTFILE}

date
time singularity exec --bind ${SCRIPTS}/.. --bind /home ${SINGULARITY} bash -c "
   mpirun -np ${STATIC_ncores} --hostfile \${HOSTFILE} ./\${executable}
"
date

grep "Finished running" log.init_atmosphere.0000.out >& /dev/null
if [ \$? -ne 0 ]; then
   echo "  BUMMER: Static generation failed for some yet unknown reason."
   echo " "
   tail -30 ${DIRRUN}/log.init_atmosphere.0000.out
   echo " "
   exit 21
fi

echo "  ####################################"
echo "  ### Static completed - \$(date) ####"
echo "  ####################################"
echo " "


mv log.init_atmosphere.0000.out ${DATAOUT}/logs/log.init_atmosphere.0000.x1.${RES}.static.nc.out


EOF0
