#!/bin/bash

cat << EOF0 > ${DIRRUN}/model.bash 
#!/bin/bash -x
#PBS -N ${MODEL_jobname}
#PBS -q ${MODEL_QUEUE}
##PBS -l select=${MODEL_nnodes}:ncpus=${MODEL_ncpn}:mpiprocs=${MODEL_ncpn}
#PBS -l select=${MODEL_nnodes}:ncpus=${MODEL_ncpn}
#PBS -l place=scatter
#PBS -l place=excl
#PBS -l walltime=${MODEL_walltime}
#PBS -j oe
#PBS -o ${DATAOUT}/${YYYYMMDDHHi}/Model/logs/model.bash.o$PBS_JOBID
#PBS -e ${DATAOUT}/${YYYYMMDDHHi}/Model/logs/model.bash.e$PBS_JOBID


export executable=atmosphere_model

ulimit -c unlimited
ulimit -v unlimited
ulimit -s unlimited

. ${SCRIPTS}/setenv.bash

cd ${DIRRUN}
chmod 775 *


export CURRENT_HOST=\$(cat \$PBS_NODEFILE)
export HOSTFILE=${DIRRUN}/hostfile
echo "\${CURRENT_HOST}" | sed "s,\..*$,," > \${HOSTFILE}

date
which singularity
time singularity exec --bind ${SCRIPTS}/.. ${SINGULARITY} bash -c "
   mpirun -np ${MODEL_ncores} --hostfile \${HOSTFILE} ./\${executable}
"
date


#
# move dataout, clean up and remove files/links
#

mv MONAN_DIAG_* ${DATAOUT}/${YYYYMMDDHHi}/Model
mv MONAN_HIST_* ${DATAOUT}/${YYYYMMDDHHi}/Model
cp -f ${EXECS}/MONAN-VERSION.txt ${DATAOUT}/${YYYYMMDDHHi}/Model
cp -f ${EXECS}/MONAN-VERSION.txt ${DATAOUT}/${YYYYMMDDHHi}/Model/logs/
cp -f ${DIRHOMES}/VERSION.txt ${DATAOUT}/${YYYYMMDDHHi}/Model/logs/SCRIPTSCDCT-VERSION.txt
cp -f ${MONANDIR}/README.md ${DATAOUT}/${YYYYMMDDHHi}/Model/logs/

mv log.atmosphere.*.out ${DATAOUT}/${YYYYMMDDHHi}/Model/logs
mv log.atmosphere.*.err ${DATAOUT}/${YYYYMMDDHHi}/Model/logs
mv namelist.atmosphere ${DATAOUT}/${YYYYMMDDHHi}/Model/logs
mv stream* ${DATAOUT}/${YYYYMMDDHHi}/Model/logs


EOF0
